[package]
name = "ladder"
version = "0.0.1"
description = ""
authors = ["David Cai <davidcai1993@yahoo.com>"]

[dependencies]
clap = "~2.19.0"
toml = "0.4.2"
serde_derive = "1.0.10"
serde = "1.0.10"
rust-crypto = "^0.2"
