[package]
authors = ["David Cai <davidcai1993@yahoo.com>"]
description = ""
name = "ladder"
version = "0.0.1"

[dependencies]
bytes = "0.4.4"
clap = "~2.19.0"
rust-crypto = "^0.2"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_json = "1.0.2"
toml = "0.4.2"
